### ISSUE TITLE
Support for short urls

### ISSUE THREAD

**Issue by YJB-Gay** [dragonismcode/fxtiktok#1]
Add support for `vm.tiktok.com` links. 

`vm.tnktok.com`

**Comment by okdargy** [comment]
aright, support for vm.tiktok links are completed. apologies for this taking so long.

(preview, top is before and bottom is after fixes)
![image](https://github.com/okdargy/fxtiktok/assets/76412158/53811fed-7204-48fc-b218-9b749d0df633)
