### ISSUE TITLE
Embeds just don't seem to appear at all

### ISSUE THREAD

**Issue by etriebe** [dragonismcode/fxtiktok#12]
![image](https://github.com/user-attachments/assets/328fa93d-0344-4ff2-b101-e7363f959074)

Just looks like a regular link. Did something change?

**Comment by okdargy** [comment]
Hey @etriebe, looks like it's working for me right now (as of 12:00 AM CST), is it possible you don't have embed privileges in the server you're sending this in?

![image](https://github.com/user-attachments/assets/dded95e5-a5c0-4e16-a178-02a49fc9e7e5)

**Comment by etriebe** [comment]
I do have perms. I'm the server owner. 

I just saw one working so I'll try again with the same URL and a different one.

**Comment by etriebe** [comment]
Yep. It's this specific URL. 

https://www.tnktok.com/t/ZP81NmQk9/

Obviously not a huge rush since it is seemingly just one link so far.

**Comment by okdargy** [comment]
It seems this is happening because the TikTok is age restricted. We use TikTok rehydration without a logged in account meaning Workers can't access the video.

**Comment by etriebe** [comment]
Ah! Good to know. Thank you!

—Eric Triebe
________________________________

**Comment by okdargy** [comment]
Added a warning in case this happens for anybody else, thanks for reporting!

![image](https://github.com/user-attachments/assets/b7c949a9-785e-41c9-b7f7-ad8ca3487f49)

**Comment by etriebe** [comment]
Perfect! That’s super helpful, thank you!
