### ISSUE TITLE
Support captions in tiktok embeds

### ISSUE THREAD

**Issue by Apocolypto** [dragonismcode/fxtiktok#13]
Currently, when you embed tiktok links, it shows the stats and the poster of the tiktok. Would it be possible to incorporate the caption as well like tfxktok does?

**Comment by okdargy** [comment]
Yes, it is very possible for videos. In fact, they are already being added with `og:description` tag but Discord only shows descriptions for images and not videos.

![image](https://github.com/user-attachments/assets/ad00a3d4-f2e4-4621-a5dc-6da2f12e9203)

I could make it like tfxktok.com where it would show on top with the `json+oembed` link but I feel it would make the embed feel way too cluttered and cramped. I could possibly add a `?addDesc` query to move the description from the `og:description` tag to the `json+oembed` link. Does that work for you?

**Comment by Apocolypto** [comment]
Yeah, that would work great!

**Comment by okdargy** [comment]
Sorry for taking so long to implement this, was busy with school and such but better late than never! 😅

![image](https://github.com/user-attachments/assets/747124a9-59df-407c-8b9c-e0f1a8844fd2)
