### ISSUE TITLE
Some tiktok embeds fail to download and we're left with a poop emoji background

### ISSUE THREAD

**Issue by etriebe** [dragonismcode/fxtiktok#16]
https://www.tnktok.com/t/ZP8eKpX8o/

I've seen this quite a bit more recently. Can't seem to figure out a pattern yet. 

<img width="347" alt="image" src="https://github.com/user-attachments/assets/c029bcc8-d88a-4184-bc1a-2f57d52731ad">

**Comment by okdargy** [comment]
Seems to be working for me, could this be related to #14? 

![image](https://github.com/user-attachments/assets/e04e4ad9-8bc4-4679-a81d-659fc5beaf80)

Also, apologies for the late reply. I have email notifications setup but my mailing service didn't send out a notification for some reason.

**Comment by okdargy** [comment]
Assuming it's related to #14, closing this issue to encourage all conversation about this issue on #14.
