### ISSUE TITLE
Slideshow embed not working with new links?

### ISSUE THREAD

**Issue by Nekuryo** [dragonismcode/fxtiktok#19]
I hope im not doing something wrong but when trying to embed a slideshow i only shows the „thumbnail“ / first picture

before link looks like:
vm.tiktok.com/[random letters/numbers]

after changing it looks like this:
vm.tnktok.com/[random letters/numbers]

**Comment by okdargy** [comment]
Are you on mobile? If so, Discord shows only one image by default.

**Comment by Nekuryo** [comment]
ohh yes, my apologies. yes i was on mobile and i just checked on pc, it works as intended 😅
