### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by GeekCornerGH** [dragonismcode/fxtiktok#2]
Hi @okdargy it seems your domain has expired, is the project discountinued?

Thanks for that amazing project

**Comment by okdargy** [comment]
Hi there, we are currently in the process of renewing our `tnktok.com` domain, thank you for your patience and the compliments on the project!

I will update this issue when it is resolved.

**Comment by okdargy** [comment]
Domain name has been transferred to Cloudflare, thank you all for your patience

![image](https://github.com/okdargy/fxTikTok/assets/76412158/b7a41c8f-a18b-4dea-a3a1-36890112f009)

**Comment by okdargy** [comment]
Alright, domain is correctly configured and is now up and running! Thank you for reporting this issue and have a nice rest of your weekend!
