### ISSUE TITLE
Videos are not playing, while the sound is

### ISSUE THREAD

**Issue by PadowYT2** [dragonismcode/fxtiktok#20]
The title sounds exactly like #14, but for me it doesn't work on any subdomains.

<details><summary>Discord debug</summary>
<p>

canary 336596 (bc0f01f) Host 0.0.504 x64 Build Override: N/A Linux 64-bit (6.8.0-45-generic)
Vencord 013c8d0 (Standalone)
Electron 32.0.0
Chromium 128.0.6613.36

</p>
</details>

https://github.com/user-attachments/assets/85035172-88ae-49f9-9b63-6673cceac678

**Comment by okdargy** [comment]
Probably related to #14, working on my client.
> stable 336973 (eba9eda) Host 1.0.9166 x64 (53429) Build Override: N/A Windows 11 64-bit (10.0.22631)
Vencord 013c8d06 (Dev)
Electron 32.0.0
Chromium 128.0.6613.36

![image](https://github.com/user-attachments/assets/6471d8fe-fa5c-4f66-965e-b9eebbb9ce02)

**Comment by PadowYT2** [comment]
Honestly, not sure if it was a timing thing, or a discord update that solved it. But somehow it works
> canary 337025 (d3ff133) Host 0.0.505 x64 Build Override: N/A Linux 64-bit (6.8.0-45-generic)
> Vencord 013c8d0 (Standalone)
> Electron 32.0.0
> Chromium 128.0.6613.36
