### ISSUE TITLE
`getVideoInfo` request is failing

### ISSUE THREAD

**Issue by NuroDev** [dragonismcode/fxtiktok#4]
### What's the issue?

I just started using this service the other week & it's been super helpful, but today I noticed that links were failing to render correctly in Discord
```
❌ Unexpected end of JSON input
An error occurred while trying to fetch the video. Please try again later.
```
After a quick clone & local test [this request](https://github.com/okdargy/fxTikTok/blob/hono-rewrite/src/services/tiktok.ts#L20) seems to be returning OK but is failing to decode the JSON payload.
This is of course likely an upstream issue but I thought I would report it in case you were aware of any possible fixes or work around since I don't know the TikTok API at all.

**Comment by okdargy** [comment]
Hm, seems like TikTok disabled that API route. I'll look into finding another API route with similar speeds.

**Comment by okdargy** [comment]
> Hm, seems like TikTok disabled that API route. I'll look into finding another API route with similar speeds.

Results (executed from Cloudflare Worker)
```json
{
	"api19-normal-c-useast2a.tiktokv.com": 1571,
	"api21-normal-c-useast2a.tiktokv.com": 1723,
	"api22-normal-c-useast2a.tiktokv.com": 1622,
	"api16-normal-c-useast2a.tiktokv.com": 1881
}
```

I'll commit a fix to update the URL, thanks for reporting!
