### ISSUE TITLE
New short urls

### ISSUE THREAD

**Issue by barraIhsan** [dragonismcode/fxtiktok#5]
#1 here, but now I see people sharing around with `vt` subdomain stead of the `vm`.
I tried to change the `vt` links to the `vm` subdomain and it works!

**Comment by okdargy** [comment]
Alrighty, I've connected the subdomain and tested it to make sure it worked on Discord. You should be able to use `vt.tnktok.com` now.

![image](https://github.com/okdargy/fxTikTok/assets/76412158/36ee540b-d3dd-4154-90ed-20a05fcf3050)

Thanks for reporting!

**Comment by okdargy** [comment]
After doing a bit of researching, I've found a little over 30 subdomains connecting to TikTok. I've connected those as well to the Cloudflare Worker.

**Comment by barraIhsan** [comment]
> After doing a bit of researching, I've found a little over 30 subdomains connecting to TikTok. I've connected those as well to the Cloudflare Worker.

oh, I literally do
`curl https://v[a-z].tiktok.com/<video id>/ -v`
to check, I forget that dns lookup exists.
