### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by okdargy** [dragonismcode/fxtiktok#6]
It seems TikTok has changed their /aweme/v1/feed endpoint on all API URLs. Using `curl` to request the data responses with an empty response and a 200 OK status.

```
https://api22-normal-c-useast2a.tiktokv.com/aweme/v1/feed/?aweme_id=...
https://api19-normal-c-useast2a.tiktokv.com/aweme/v1/feed/?aweme_id=...
https://api22-normal-c-useast1a.tiktokv.com/aweme/v1/feed/?aweme_id=...
```

This has also become an issue in [yt-dlp](https://github.com/yt-dlp/yt-dlp/issues/9506) as well.

**Comment by barraIhsan** [comment]
![image](https://github.com/okdargy/fxTikTok/assets/57800056/6038dec7-7363-4216-ad2e-f6f16a51b514)
Yeah, and now it now shows the embed without the video instead

**Comment by okdargy** [comment]
> Yeah, and now it now shows the embed without the video instead

Apologies, that was when I pushed a temporary (silent) fix on the 24th to switch to the `tikwm.com` API (thanks @BlueberryWolf) but it didn't provide the height or width of the video so it couldn't have been embedded into Discord.

Anyway, a6f715a826be09ea578e208d0aaadae9a576bd56 has been pushed and now we should be up and running. Thank you all for your patience and supporting this project (and also the yt-dlp community for finding a fix so fast)
