### ISSUE TITLE
Support multiple images and sound in slideshows

### ISSUE THREAD

**Issue by D3SOX** [dragonismcode/fxtiktok#8]
Title says it. Currently, when you try to send a slideshow, it only shows the first image and has no sound.
As per solutions, I thought about using something like `ffmpeg` to make a slideshow out of it and embed the sound.
If that's not feasible we could also just embed all images like [ddinstagram](https://github.com/Wikidepia/InstaFix) does it and ignore the sound

**Comment by okdargy** [comment]
I'll definitely look into implementing this! Although this would have to be a separate repository or branch and written in a faster language such as Rust or Go, hosted on a personal VPS since Workers doesn't support `ffmpeg`

**Comment by okdargy** [comment]
After looking more into meta tags, I realized you can just include more images into the `head` and it'll embed them! 😅

![image](https://github.com/okdargy/fxTikTok/assets/76412158/1cbef81e-3df8-4bee-98ef-312571fe7dd8)

Thank you for suggesting, feel free to open another issue for any bugs you encounter or future features you would like to see!
